name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Your GitHub username
          password: ${{ secrets.TOKEN_GITHUB }} # GitHub-provided token

      - name: Build and Push Docker image to GHCR
        run: |
          docker build -t ghcr.io/bhatt-dev/buildmyfolio-backend:latest .
          docker push ghcr.io/bhatt-dev/buildmyfolio-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 public IP
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }} # SSH private key
          script: |
            docker stop buildmyfolio-backend || true
            docker rm buildmyfolio-backend || true
            docker pull ghcr.io/bhatt-dev/buildmyfolio-backend:latest
            docker run -d --name buildmyfolio-backend \
              -p 5000:5000 \
              -e PORT=${{ secrets.PORT }} \
              ghcr.io/bhatt-dev/buildmyfolio-backend:latest